# Generated by Django 5.1.4 on 2026-03-15 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("rides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverLocation",
            fields=[
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="current_location",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("heading", models.FloatField(blank=True, null=True)),
                ("speed_kmh", models.FloatField(blank=True, null=True)),
                ("accuracy_meters", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "driver_locations",
            },
        ),
        migrations.CreateModel(
            name="TripLocationSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("heading", models.FloatField(blank=True, null=True)),
                ("speed_kmh", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_snapshots",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "db_table": "trip_location_snapshots",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ride", "timestamp"],
                        name="trip_locati_ride_id_e3b97b_idx",
                    )
                ],
            },
        ),
    ]
