# Generated by Django 5.1.4 on 2026-03-15 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ride_requested", "Ride Requested"),
                            ("driver_assigned", "Driver Assigned"),
                            ("driver_arrived", "Driver Arrived"),
                            ("trip_started", "Trip Started"),
                            ("trip_completed", "Trip Completed"),
                            ("ride_cancelled", "Ride Cancelled"),
                            ("payment_received", "Payment Received"),
                            ("account_approved", "Account Approved"),
                            ("general", "General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    )
                ],
            },
        ),
    ]
