# Generated by Django 5.1.4 on 2026-07-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_add_payment_debited_and_shared_ride_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ride_requested', 'Ride Requested'), ('driver_assigned', 'Driver Assigned'), ('driver_en_route', 'Driver En Route'), ('driver_arrived', 'Driver Arrived'), ('trip_started', 'Trip Started'), ('trip_completed', 'Trip Completed'), ('ride_cancelled', 'Ride Cancelled'), ('payment_received', 'Payment Received'), ('payment_debited', 'Payment Debited'), ('shared_ride_joined', 'Shared Ride Joined'), ('shared_ride_confirmed', 'Shared Ride Confirmed'), ('shared_ride_dispatched', 'Shared Ride Dispatched'), ('shared_ride_cancelled', 'Shared Ride Cancelled'), ('account_approved', 'Account Approved'), ('verification_submitted', 'Verification Submitted'), ('broadcast', 'Broadcast'), ('system_alert', 'System Alert'), ('support_ticket', 'Support Ticket'), ('general', 'General')], max_length=30),
        ),
    ]
