# Generated by Django 5.1.4 on 2026-03-15 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FareConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "Motorcycle"),
                            ("tricycle", "Tricycle (Keke)"),
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("minivan", "Minivan / Shuttle"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=8)),
                ("per_km_rate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("minimum_fare", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "booking_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("surge_enabled", models.BooleanField(default=False)),
                (
                    "max_surge_multiplier",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fare_configurations",
                "ordering": ["-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["vehicle_type", "is_active"],
                        name="fare_config_vehicle_f56e35_idx",
                    )
                ],
            },
        ),
    ]
