# Generated by Django 5.1.4 on 2026-06-07 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.15, help_text='Platform commission as a decimal (e.g., 0.15 = 15%)', max_digits=5)),
                ('distance_provider', models.CharField(choices=[('haversine', 'Haversine (Fallback)'), ('osrm', 'OSRM Routing (Primary)'), ('google', 'Google Distance Matrix')], default='haversine', max_length=20)),
                ('max_distance_km', models.DecimalField(decimal_places=2, default=150.0, help_text='Maximum distance allowed for ride requests in KM', max_digits=6)),
                ('no_show_fee_enabled', models.BooleanField(default=True)),
                ('no_show_fee_amount', models.DecimalField(decimal_places=2, default=200.0, help_text='Fee charged to student after no-show timeout', max_digits=8)),
                ('no_show_wait_minutes', models.PositiveSmallIntegerField(default=5, help_text='Minutes driver must wait before no-show can be triggered')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
    ]
