# Generated by Django 5.1.4 on 2026-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_platformsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fareconfiguration',
            name='vehicle_type',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('tricycle', 'Tricycle'), ('sedan', 'Sedan'), ('mpv', 'MPV'), ('minibus', 'Minibus'), ('coach', 'Coach')], db_index=True, max_length=20),
        ),
    ]
