# Generated by Codex on 2026-07-18

from django.db import migrations, models


def move_default_provider_to_osrm(apps, schema_editor):
    PlatformSettings = apps.get_model('pricing', 'PlatformSettings')
    PlatformSettings.objects.filter(distance_provider='haversine').update(distance_provider='osrm')


def move_default_provider_to_haversine(apps, schema_editor):
    PlatformSettings = apps.get_model('pricing', 'PlatformSettings')
    PlatformSettings.objects.filter(distance_provider='osrm').update(distance_provider='haversine')


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_platformsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='distance_provider',
            field=models.CharField(
                choices=[
                    ('haversine', 'Haversine (Fallback)'),
                    ('osrm', 'OSRM Routing (Primary)'),
                    ('google', 'Google Directions'),
                ],
                default='osrm',
                max_length=20,
            ),
        ),
        migrations.RunPython(move_default_provider_to_osrm, move_default_provider_to_haversine),
    ]
