# Generated by Django 5.1.4 on 2026-07-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_fareconfiguration_vehicle_type'),
        ('pricing', '0003_platformsettings_default_osrm'),
    ]

    operations = [
    ]
