# Generated by Django 5.1.4 on 2026-07-19 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_merge_20260719_1739'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteGraphVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'route_graph_versions',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteLane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('geometry', models.JSONField(help_text='List of {lat, lng} coordinate dictionaries')),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('direction', models.CharField(choices=[('two_way', 'Two-way'), ('one_way', 'One-way')], default='two_way', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('priority', models.CharField(default='main', max_length=50)),
                ('allowed_vehicles', models.JSONField(default=list, help_text='List of allowed vehicle types, e.g. ["motorbike", "sedan"]')),
                ('graph_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='pricing.routegraphversion')),
            ],
            options={
                'db_table': 'route_lanes',
            },
        ),
    ]
