# Generated by Django 5.1.4 on 2026-03-15 11:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating_type",
                    models.CharField(
                        choices=[
                            ("student_to_driver", "Student to Driver"),
                            ("driver_to_student", "Driver to Student"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ratee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "db_table": "ratings",
                "indexes": [
                    models.Index(
                        fields=["ratee", "rating_type"],
                        name="ratings_ratee_i_96ad8f_idx",
                    ),
                    models.Index(fields=["ride"], name="ratings_ride_id_e21d9a_idx"),
                ],
                "unique_together": {("ride", "rater", "rating_type")},
            },
        ),
    ]
