# Generated by Django 5.1.4 on 2026-04-30 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('searching', 'Searching for Driver'), ('driver_assigned', 'Driver Assigned'), ('driver_en_route', 'Driver En Route'), ('driver_arrived', 'Driver Arrived'), ('in_progress', 'Trip In Progress'), ('completed', 'Completed'), ('cancelled_by_student', 'Cancelled by Student'), ('cancelled_by_driver', 'Cancelled by Driver'), ('cancelled_no_driver', 'Cancelled - No Driver Found'), ('disputed', 'Disputed')], db_index=True, default='requested', max_length=30)),
                ('vehicle_type_requested', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('tricycle', 'Tricycle (Keke)'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('minivan', 'Minivan / Shuttle')], default='sedan', max_length=20)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actual_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('base_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('total_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('wallet', 'Wallet'), ('card', 'Card'), ('cash', 'Cash')], default='cash', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_activated', models.BooleanField(default=False)),
                ('shared_with_contacts', models.JSONField(blank=True, default=list)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('driver_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('driver_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('trip_started_at', models.DateTimeField(blank=True, null=True)),
                ('trip_completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rides',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverRideRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('timed_out', 'Timed Out')], default='pending', max_length=10)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests_received', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_requests', to='rides.ride')),
            ],
            options={
                'db_table': 'driver_ride_requests',
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'requested_at'], name='rides_status_243aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['student', 'status'], name='rides_student_3a322e_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='rides_driver__d736b9_idx'),
        ),
        migrations.AddIndex(
            model_name='driverriderequest',
            index=models.Index(fields=['ride', 'response'], name='driver_ride_ride_id_ed4e98_idx'),
        ),
        migrations.AddIndex(
            model_name='driverriderequest',
            index=models.Index(fields=['driver', 'offered_at'], name='driver_ride_driver__e8b66a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverriderequest',
            unique_together={('ride', 'driver')},
        ),
    ]
