# Generated by Django 5.1.4 on 2026-05-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="no_show_fee_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="no_show_marked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="requested_seats",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ride",
            name="scheduled_pickup_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("searching", "Searching for Driver"),
                    ("driver_assigned", "Driver Assigned"),
                    ("driver_en_route", "Driver En Route"),
                    ("driver_arrived", "Driver Arrived"),
                    ("in_progress", "Trip In Progress"),
                    ("completed", "Completed"),
                    ("cancelled_by_student", "Cancelled by Student"),
                    ("cancelled_by_driver", "Cancelled by Driver"),
                    ("cancelled_no_driver", "Cancelled - No Driver Found"),
                    ("cancelled_no_show", "Cancelled - No Show"),
                    ("disputed", "Disputed"),
                ],
                db_index=True,
                default="requested",
                max_length=30,
            ),
        ),
    ]
