# Generated by Django 5.1.4 on 2026-05-17 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_no_show_fee_amount_ride_no_show_marked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageRide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique token encoded in the QR code. One per ride creation.', unique=True)),
                ('reference', models.CharField(db_index=True, max_length=24, unique=True)),
                ('origin_address', models.CharField(max_length=255)),
                ('origin_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_address', models.CharField(max_length=255)),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('tricycle', 'Tricycle (Keke)'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('minivan', 'Minivan / Shuttle')], default='sedan', max_length=20)),
                ('total_seats', models.PositiveSmallIntegerField(default=4)),
                ('booked_seats', models.PositiveSmallIntegerField(default=0)),
                ('fare_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open (Accepting Passengers)'), ('full', 'Full'), ('departed', 'Departed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('driver_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='QR auto-expires after this time (optional).', null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garage_rides_as_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'garage_rides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GarageRidePassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seats_booked', models.PositiveSmallIntegerField(default=1)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet_transaction_reference', models.CharField(blank=True, max_length=40)),
                ('boarded_at', models.DateTimeField(auto_now_add=True)),
                ('garage_ride', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='rides.garageride')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garage_ride_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'garage_ride_passengers',
                'ordering': ['-boarded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='garageride',
            index=models.Index(fields=['driver', 'status'], name='garage_ride_driver__ab63ad_idx'),
        ),
        migrations.AddIndex(
            model_name='garageride',
            index=models.Index(fields=['status', 'created_at'], name='garage_ride_status_ad0079_idx'),
        ),
        migrations.AddIndex(
            model_name='garageridepassenger',
            index=models.Index(fields=['garage_ride', 'boarded_at'], name='garage_ride_garage__2c052e_idx'),
        ),
        migrations.AddIndex(
            model_name='garageridepassenger',
            index=models.Index(fields=['student', 'boarded_at'], name='garage_ride_student_421eb4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='garageridepassenger',
            unique_together={('garage_ride', 'student')},
        ),
    ]
