# Generated by Django 5.1.4 on 2026-06-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_mapsettings_and_more'),
        ('rides', '0005_driver_saved_routes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=24, unique=True)),
                ('departure_date', models.DateField()),
                ('window_start', models.TimeField()),
                ('window_end', models.TimeField()),
                ('join_deadline', models.DateTimeField()),
                ('origin_address', models.CharField(max_length=255)),
                ('origin_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_address', models.CharField(max_length=255)),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('vehicle_size', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('minivan', 'Minivan'), ('minibus', 'Minibus'), ('bus', 'Bus')], default='bus', max_length=20)),
                ('cargo_capacity_kg', models.PositiveIntegerField(default=0)),
                ('accessibility_features', models.JSONField(blank=True, default=list)),
                ('standard_enabled', models.BooleanField(default=True)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('standing_enabled', models.BooleanField(default=False)),
                ('standing_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('premium_enabled', models.BooleanField(default=False)),
                ('premium_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freight_enabled', models.BooleanField(default=False)),
                ('freight_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduled_rides',
                'ordering': ['departure_date', 'window_start'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledRidePassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pricing_tier', models.CharField(choices=[('standard', 'Standard'), ('standing', 'Standing'), ('premium', 'Premium'), ('freight', 'Freight')], max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=40)),
                ('cargo_description', models.TextField(blank=True)),
                ('cargo_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('boarded', 'Boarded'), ('alighted', 'Alighted'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scheduled_ride_passengers',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledRideStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estimated_arrival_offset_min', models.PositiveSmallIntegerField(default=0)),
                ('is_pickup', models.BooleanField(default=True)),
                ('is_dropoff', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scheduled_ride_stops',
                'ordering': ['ride', 'order'],
            },
        ),
        migrations.RenameIndex(
            model_name='driversavedroute',
            new_name='driver_save_driver__fb4665_idx',
            old_name='driver_sav_driver__e4934d_idx',
        ),
        migrations.RenameIndex(
            model_name='driversavedroute',
            new_name='driver_save_driver__cc07db_idx',
            old_name='driver_sav_driver__e0f2a2_idx',
        ),
        migrations.AlterField(
            model_name='garageride',
            name='status',
            field=models.CharField(choices=[('open', 'Open (Accepting Passengers)'), ('full', 'Full'), ('departed', 'Departed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduledride',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_rides_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledride',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_rides', to='accounts.campus'),
        ),
        migrations.AddField(
            model_name='scheduledride',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_rides_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledridepassenger',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='rides.scheduledride'),
        ),
        migrations.AddField(
            model_name='scheduledridepassenger',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_ride_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledridestop',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rides.scheduledride'),
        ),
        migrations.AddField(
            model_name='scheduledridepassenger',
            name='alighting_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alighting_passengers', to='rides.scheduledridestop'),
        ),
        migrations.AddField(
            model_name='scheduledridepassenger',
            name='boarding_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarding_passengers', to='rides.scheduledridestop'),
        ),
        migrations.AddIndex(
            model_name='scheduledride',
            index=models.Index(fields=['campus', 'status', 'departure_date'], name='scheduled_r_campus__90347e_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledride',
            index=models.Index(fields=['status', 'join_deadline'], name='scheduled_r_status_9e783b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledride',
            index=models.Index(fields=['created_by', 'departure_date'], name='scheduled_r_created_a60657_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledride',
            index=models.Index(fields=['assigned_driver', 'departure_date'], name='scheduled_r_assigne_f9eca3_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledridestop',
            index=models.Index(fields=['ride', 'order'], name='scheduled_r_ride_id_bb2916_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledridestop',
            unique_together={('ride', 'order')},
        ),
        migrations.AddIndex(
            model_name='scheduledridepassenger',
            index=models.Index(fields=['ride', 'status'], name='scheduled_r_ride_id_85db70_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledridepassenger',
            index=models.Index(fields=['student', 'joined_at'], name='scheduled_r_student_f45ea7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledridepassenger',
            unique_together={('ride', 'student')},
        ),
    ]
