# Generated by Django 5.1.4 on 2026-06-07 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_scheduledride_scheduledridepassenger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledridepassenger',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledridepassenger',
            name='seat_type',
            field=models.CharField(choices=[('seated', 'Seated'), ('standing', 'Standing')], default='seated', max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduledRideBusAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bus_label', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('seated_capacity', models.PositiveIntegerField()),
                ('standing_capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('boarding', 'Boarding'), ('loading', 'Loading'), ('departed', 'Departed'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_bus_assignments', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignments', to='rides.scheduledride')),
            ],
            options={
                'db_table': 'scheduled_ride_bus_assignments',
                'ordering': ['ride', 'order'],
            },
        ),
        migrations.AddField(
            model_name='scheduledridepassenger',
            name='bus_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_passengers', to='rides.scheduledridebusassignment'),
        ),
        migrations.AddIndex(
            model_name='scheduledridebusassignment',
            index=models.Index(fields=['ride', 'status'], name='scheduled_r_ride_id_037fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledridebusassignment',
            index=models.Index(fields=['driver', 'status'], name='scheduled_r_driver__36562d_idx'),
        ),
    ]
