# Generated by Django 5.1.4 on 2026-06-07 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_scheduledridepassenger_checked_in_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledridebusassignment',
            name='bus_label',
            field=models.CharField(help_text='e.g. Bus A, Bus 1', max_length=60),
        ),
        migrations.AlterField(
            model_name='scheduledridebusassignment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduledridebusassignment',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Departure sequence'),
        ),
        migrations.AlterField(
            model_name='scheduledridebusassignment',
            name='seated_capacity',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledridebusassignment',
            unique_together={('ride', 'order')},
        ),
        migrations.AddIndex(
            model_name='scheduledridepassenger',
            index=models.Index(fields=['bus_assignment', 'seat_type'], name='scheduled_r_bus_ass_4cc04a_idx'),
        ),
    ]
