# Generated by Django 5.1.4 on 2026-06-07 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_alter_scheduledridebusassignment_bus_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRideDriverInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('assigned', 'Assigned'), ('declined', 'Declined')], default='interested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_ride_interests', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_drivers', to='rides.scheduledride')),
            ],
            options={
                'db_table': 'scheduled_ride_driver_interests',
                'ordering': ['-created_at'],
                'unique_together': {('ride', 'driver')},
            },
        ),
    ]
