# Generated by Django 5.1.4 on 2026-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0009_scheduledridedriverinterest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledride",
            name="vehicle_size",
        ),
        migrations.AddField(
            model_name="scheduledride",
            name="allowed_vehicle_types",
            field=models.JSONField(
                default=list, help_text="List of eligible VehicleClass string values"
            ),
        ),
    ]
