# Generated by Django 5.1.4 on 2026-06-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_remove_scheduledride_vehicle_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garageride',
            name='vehicle_type',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('tricycle', 'Tricycle'), ('sedan', 'Sedan'), ('mpv', 'MPV'), ('minibus', 'Minibus'), ('coach', 'Coach')], default='sedan', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type_requested',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('tricycle', 'Tricycle'), ('sedan', 'Sedan'), ('mpv', 'MPV'), ('minibus', 'Minibus'), ('coach', 'Coach')], default='sedan', max_length=20),
        ),
    ]
