# Generated by Django 5.1.4 on 2026-06-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_alter_garageride_vehicle_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledride',
            name='accessibility_features',
        ),
    ]
