# Generated by Django 5.1.4 on 2026-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_remove_scheduledride_accessibility_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='garageridepassenger',
            name='ticket_ref',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scheduledridepassenger',
            name='ticket_ref',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
    ]
