# Generated by Codex on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_garageridepassenger_ticket_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='estimated_route_geometry',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ride',
            name='route_distance_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='ride',
            name='route_confidence',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='route_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
