# Generated by Django 5.1.4 on 2026-07-25 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_ride_route_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=20, unique=True)),
                ('share_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('vehicle_type', models.CharField(choices=[('motorbike', 'Motorbike'), ('tricycle', 'Tricycle'), ('sedan', 'Sedan'), ('mpv', 'MPV'), ('minibus', 'Minibus'), ('coach', 'Coach')], default='sedan', max_length=20)),
                ('dropoff_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('max_riders', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('gathering', 'Gathering'), ('ready', 'Ready'), ('matching', 'Matching'), ('matched', 'Matched'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='gathering', max_length=20)),
                ('anchor_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('anchor_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shared_rides', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_rides', to='rides.ride')),
            ],
            options={
                'db_table': 'shared_rides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedRideRider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_address', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('fare_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('shared_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='rides.sharedride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_ride_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_ride_riders',
                'unique_together': {('shared_ride', 'user')},
            },
        ),
    ]
