# Generated by Django 5.1.4 on 2026-08-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_sharedride_sharedriderider'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='pending_completion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('searching', 'Searching for Driver'), ('driver_assigned', 'Driver Assigned'), ('driver_en_route', 'Driver En Route'), ('driver_arrived', 'Driver Arrived'), ('in_progress', 'Trip In Progress'), ('pending_completion', 'Pending Completion'), ('completed', 'Completed'), ('cancelled_by_student', 'Cancelled by Student'), ('cancelled_by_driver', 'Cancelled by Driver'), ('cancelled_no_driver', 'Cancelled - No Driver Found'), ('cancelled_no_show', 'Cancelled - No Show'), ('disputed', 'Disputed')], db_index=True, default='requested', max_length=30),
        ),
    ]
