# Generated by Codex on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_ride_pending_completion_at_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='garageride',
            name='estimated_distance_km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
