# Generated by Codex on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_garageride_estimated_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='garageride',
            name='estimated_route_geometry',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
