# Generated by Django 5.1.4 on 2026-08-18 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_garageride_estimated_route_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRideActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='rides.scheduledride')),
            ],
            options={
                'db_table': 'scheduled_ride_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
