# Generated by Django 5.1.4 on 2026-08-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0019_add_scheduled_ride_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledride',
            name='reminder_15m_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledride',
            name='reminder_60m_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduledridedriverinterest',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('assigned', 'Assigned'), ('declined', 'Declined'), ('withdrawn_with_fine', 'Withdrawn (Fine Applied)')], default='interested', max_length=30),
        ),
    ]
