import { memo } from 'react'
import type { CSSProperties, MouseEvent } from 'react'
import type { LucideIcon } from 'lucide-react'
import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  Badge,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  BellRing,
  BookOpen,
  Bookmark,
  Brain,
  Cable,
  Calendar,
  CalendarDays,
  Cast,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Church,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleHelp,
  CirclePlay,
  Clapperboard,
  Clock,
  Cloud,
  Columns3,
  Construction,
  Copy,
  CreditCard,
  Database,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  Flame,
  FlaskConical,
  FolderOpen,
  Gavel,
  Globe2,
  Grid2X2,
  GripVertical,
  HandHeart,
  Headphones,
  Heart,
  History,
  Home,
  Hourglass,
  Image,
  ImagePlus,
  Info,
  Landmark,
  LayoutDashboard,
  Leaf,
  LibraryBig,
  Link,
  List,
  ListPlus,
  Lock,
  LockKeyhole,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MailWarning,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  Moon,
  MoreVertical,
  Music,
  Network,
  Newspaper,
  Palette,
  Pencil,
  Phone,
  PiggyBank,
  Plane,
  Play,
  Plus,
  Podcast,
  Printer,
  ReceiptText,
  RefreshCcw,
  RefreshCw,
  Rss,
  School,
  Search,
  SearchX,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Siren,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Target,
  Timer,
  ToggleRight,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Upload,
  User,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  WalletCards,
  X,
  Zap,
} from 'lucide-react'

interface IconProps {
  name: string
  size?: number | string
  className?: string
  color?: string
  title?: string
  ariaLabel?: string
  ariaHidden?: boolean
  onClick?: (event: MouseEvent<SVGSVGElement>) => void
  style?: CSSProperties
  'data-testid'?: string
}

const iconMapping: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_tree: Network,
  add: Plus,
  add_photo_alternate: ImagePlus,
  admin_panel_settings: ShieldCheck,
  analytics: BarChart3,
  api: Cable,
  archive: Archive,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  article: Newspaper,
  auto_stories: LibraryBig,
  backup: Cloud,
  badge: Badge,
  bar_chart: BarChart3,
  block: CircleAlert,
  bolt: Zap,
  book: BookOpen,
  bookmark: Bookmark,
  calendar: Calendar,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  campaign: Megaphone,
  cast: Cast,
  chat: MessageCircle,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  church: Church,
  circle: Circle,
  close: X,
  cloud: Cloud,
  collections_bookmark: LibraryBig,
  comment: MessageSquare,
  construction: Construction,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  dark_mode: Moon,
  delete: Trash2,
  delete_forever: Trash2,
  description: FileText,
  download: Download,
  drag_indicator: GripVertical,
  eco: Sprout,
  edit: Pencil,
  edit_note: Pencil,
  email: Mail,
  emergency: Siren,
  error: CircleAlert,
  error_outline: CircleAlert,
  event: CalendarDays,
  expand_more: ChevronsUpDown,
  family_restroom: Users,
  favorite: Heart,
  file_copy: Copy,
  filter_list_off: SearchX,
  fingerprint: Fingerprint,
  flame: Flame,
  flight: Plane,
  folder_open: FolderOpen,
  forum: MessageCircle,
  gavel: Gavel,
  grid_view: Grid2X2,
  group: Users,
  group_work: Users,
  groups: Users,
  groups_2: Users,
  headphones: Headphones,
  help: CircleHelp,
  help_outline: CircleHelp,
  history: History,
  home: Home,
  hourglass_empty: Hourglass,
  image: Image,
  info: Info,
  insights: BarChart3,
  keyboard_arrow_down: ArrowDown,
  keyboard_arrow_up: ArrowUp,
  library_books: LibraryBig,
  light_mode: Sun,
  lightbulb: Sparkles,
  link: Link,
  location_on: MapPin,
  lock: Lock,
  lock_open: LockOpen,
  lock_reset: LockKeyhole,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  manage_accounts: UserCog,
  manage_search: Search,
  mark_email_read: MailCheck,
  mark_email_unread: MailWarning,
  menu: Menu,
  menu_book: BookOpen,
  mic: Mic,
  more_vert: MoreVertical,
  movie: Clapperboard,
  music_note: Music,
  nature: Leaf,
  notifications: Bell,
  notifications_active: BellRing,
  open_in_new: ExternalLink,
  palette: Palette,
  payments: Banknote,
  pending: Timer,
  person: User,
  person_add: UserPlus,
  phone: Phone,
  play_arrow: Play,
  play_circle: CirclePlay,
  playlist_add: ListPlus,
  podcasts: Podcast,
  print: Printer,
  progress_activity: RefreshCw,
  psychology: Brain,
  public: Globe2,
  publish: Upload,
  receipt: ReceiptText,
  receipt_long: ReceiptText,
  refresh: RefreshCcw,
  remove: Minus,
  rss_feed: Rss,
  savings: PiggyBank,
  schedule: Clock,
  school: School,
  science: FlaskConical,
  search: Search,
  search_off: SearchX,
  security: Shield,
  self_improvement: Sparkles,
  send: Send,
  settings: Settings,
  share: Share2,
  shield: Shield,
  show_chart: TrendingUp,
  spa: Sparkles,
  star: Star,
  storage: Database,
  summarize: FileSpreadsheet,
  target: Target,
  toggle_on: ToggleRight,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  unfold_more: ChevronsUpDown,
  upload: Upload,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  view_kanban: Columns3,
  view_list: List,
  view_week: Columns3,
  visibility: Eye,
  visibility_off: EyeOff,
  volunteer_activism: HandHeart,
  wallet: Wallet,
  warning: TriangleAlert,
  workspace_premium: Award,
}

const Icon = memo(function Icon({
  name,
  size = 24,
  className = '',
  color = 'currentColor',
  title,
  ariaLabel,
  ariaHidden,
  onClick,
  style,
  'data-testid': testId,
}: IconProps) {
  const IconComponent = iconMapping[name] ?? CircleHelp
  const sizeValue = typeof size === 'number' ? size : Number.parseInt(size, 10) || 24

  return (
    <IconComponent
      size={sizeValue}
      color={color}
      className={className}
      aria-label={ariaLabel}
      aria-hidden={ariaHidden}
      onClick={onClick}
      style={{ display: 'inline-flex', ...style }}
      data-testid={testId}
    >
      {title ? <title>{title}</title> : null}
    </IconComponent>
  )
})

export default Icon
