# Generated by Django 5.1.4 on 2026-03-14 14:03

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True, max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("driver", "Driver"),
                            ("admin", "Admin"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/%Y/%m/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("failed_login_attempts", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("data_consent_given", models.BooleanField(default=False)),
                ("data_consent_timestamp", models.DateTimeField(blank=True, null=True)),
                ("fcm_token", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "Motorcycle"),
                            ("tricycle", "Tricycle (Keke)"),
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("minivan", "Minivan / Shuttle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vehicle_make", models.CharField(max_length=80)),
                ("vehicle_model", models.CharField(max_length=80)),
                ("vehicle_year", models.PositiveSmallIntegerField()),
                ("vehicle_color", models.CharField(max_length=40)),
                ("plate_number", models.CharField(max_length=20, unique=True)),
                ("vehicle_seats", models.PositiveSmallIntegerField(default=4)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_online", models.BooleanField(db_index=True, default=False)),
                ("is_on_trip", models.BooleanField(default=False)),
                (
                    "wallet_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                ("total_trips", models.PositiveIntegerField(default=0)),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "acceptance_rate",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "cancellation_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_drivers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "driver_profiles",
            },
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("phone_verification", "Phone Verification"),
                            ("login", "Login"),
                            ("password_reset", "Password Reset"),
                            ("transaction_pin", "Transaction PIN"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "otp_verifications",
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matric_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("department", models.CharField(blank=True, max_length=150)),
                ("level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("campus", models.CharField(default="Gidan Kwano", max_length=100)),
                (
                    "wallet_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_trips", models.PositiveIntegerField(default=0)),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_rating_given",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_verified"], name="users_is_acti_6b2a46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driverprofile",
            index=models.Index(
                fields=["is_online", "verification_status"],
                name="driver_prof_is_onli_e28aa2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driverprofile",
            index=models.Index(
                fields=["vehicle_type"], name="driver_prof_vehicle_4878ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["phone_number", "purpose", "is_used"],
                name="otp_verific_phone_n_fd5d27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["expires_at"], name="otp_verific_expires_e91cd1_idx"
            ),
        ),
    ]
