# Generated by Django 5.1.4 on 2026-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_session_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
