# Generated by Django 5.1.4 on 2026-05-23 20:50

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('phone_verification', 'Phone Verification'), ('login', 'Login'), ('password_reset', 'Password Reset'), ('transaction_pin', 'Transaction PIN'), ('email_change', 'Email Change'), ('password_change', 'Password Change')], max_length=30),
        ),
    ]
