# Generated by Django 5.1.4 on 2026-05-23 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_email_otp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSignupVerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('code_expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verification_token', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('verification_token_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_signup_verification_sessions',
                'indexes': [
                    models.Index(fields=['email', 'is_verified', 'consumed_at'], name='student_sig_email_05fc90_idx'),
                    models.Index(fields=['created_at'], name='student_sig_created_ca0d82_idx'),
                ],
            },
        ),
    ]
