# Generated by GitHub Copilot on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_driverprofile_fleet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='daily_goal_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
