# Generated by Django 5.1.4 on 2026-06-07 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_provider', models.CharField(choices=[('google', 'Google Maps'), ('mapbox', 'Mapbox GL'), ('osrm', 'OSRM Self-Hosted')], default='google', max_length=20)),
                ('custom_style_json', models.TextField(blank=True, default='[\n  {\n    "featureType": "landscape.man_made",\n    "elementType": "geometry.fill",\n    "stylers": [{"color": "#f9f9f9"}]\n  },\n  {\n    "featureType": "poi.business",\n    "stylers": [{"visibility": "off"}]\n  }\n]')),
                ('live_traffic_enabled', models.BooleanField(default=True)),
                ('demand_heatmaps_enabled', models.BooleanField(default=True)),
                ('driver_clustering_enabled', models.BooleanField(default=False)),
                ('refresh_interval_seconds', models.IntegerField(default=15)),
                ('prefer_main_roads_weight', models.IntegerField(default=85)),
                ('avoid_pedestrian_weight', models.IntegerField(default=95)),
                ('speed_limit_enforcement_weight', models.IntegerField(default=50)),
                ('geofence_buffer_meters', models.IntegerField(default=50)),
                ('pois', models.JSONField(blank=True, default=list)),
                ('idle_driver_icon', models.CharField(default='Standard Car (Green)', max_length=50)),
                ('cluster_threshold_zoom', models.IntegerField(default=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Map Settings',
                'verbose_name_plural': 'Map Settings',
                'db_table': 'map_settings',
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_391715_idx',
            old_name='audit_logs_action_created_idx',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('phone_verification', 'Phone Verification'), ('login', 'Login'), ('password_reset', 'Password Reset'), ('transaction_pin', 'Transaction PIN'), ('two_factor', 'Two-Factor Auth'), ('email_change', 'Email Change'), ('password_change', 'Password Change')], max_length=30),
        ),
    ]
