# Generated by Django 5.1.4 on 2026-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_mapsettings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("motorbike", "Motorbike"),
                    ("tricycle", "Tricycle"),
                    ("sedan", "Sedan"),
                    ("mpv", "MPV"),
                    ("minibus", "Minibus"),
                    ("coach", "Coach"),
                ],
                max_length=20,
            ),
        ),
    ]
