# Generated by Django 5.1.4 on 2026-06-21 18:58

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user_profile_photo_path),
        ),
    ]
