# Generated by Django 5.1.4 on 2026-07-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='email_announcements',
            field=models.BooleanField(default=True, help_text='Send email when an in-app announcement is broadcast.'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_rides',
            field=models.BooleanField(default=True, help_text='Send email for ride status updates (assigned, started, completed).'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_transactions',
            field=models.BooleanField(default=True, help_text='Send email for wallet top-ups, payments, and deductions.'),
        ),
    ]
