# Generated by Django 5.1.4 on 2026-07-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_usersettings_email_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='notif_driver_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notif_driver_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notif_driver_en_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notif_promotions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notif_ride_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notif_ride_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notif_sound_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notif_trip_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notif_trip_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notif_wallet_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notif_wallet_debit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='email_announcements',
            field=models.BooleanField(default=False, help_text='Send email when an in-app announcement is broadcast.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='email_rides',
            field=models.BooleanField(default=False, help_text='Send email for ride status updates (assigned, started, completed).'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='email_transactions',
            field=models.BooleanField(default=False, help_text='Send email for wallet top-ups, payments, and deductions.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='push_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
