# Generated by Django 5.1.4 on 2026-07-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_usersettings_offline_pin_verifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='notif_driver_arrived',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notif_driver_assigned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notif_driver_en_route',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notif_promotions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notif_ride_cancelled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notif_ride_requested',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notif_sound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notif_trip_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notif_trip_started',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notif_wallet_credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notif_wallet_debit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='push_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
