# Generated by Codex on 2026-08-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_backfill_driverprofile_vehicle_seats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapsettings',
            name='custom_style_json',
        ),
        migrations.AddField(
            model_name='mapsettings',
            name='config_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mapsettings',
            name='change_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mapsettings',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='map_setting_updates',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('login', 'Login'),
                    ('logout', 'Logout'),
                    ('password_change', 'Password Change'),
                    ('role_change', 'Role Change'),
                    ('wallet_credit', 'Wallet Credit'),
                    ('wallet_debit', 'Wallet Debit'),
                    ('payment_webhook', 'Payment Webhook'),
                    ('integration_update', 'Integration Update'),
                    ('map_config_update', 'Map Config Update'),
                    ('user_update', 'User Update'),
                    ('other', 'Other'),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
