# Generated by Django 5.1.4 on 2026-08-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_mapsettings_operational_governance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsettings',
            name='default_map_type',
            field=models.CharField(choices=[('roadmap', 'Roadmap (Default)'), ('satellite', 'Satellite')], default='roadmap', max_length=20),
        ),
    ]
