# Generated by Django 5.1.4 on 2026-08-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_mapsettings_default_map_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='default_map_type',
            field=models.CharField(choices=[('roadmap', 'Roadmap (Default)'), ('hybrid', 'Satellite (with roads & labels)')], default='roadmap', max_length=20),
        ),
    ]
