# Generated by Codex on 2026-08-15

from django.db import migrations, models


def set_existing_map_settings_to_hybrid(apps, schema_editor):
    MapSettings = apps.get_model('accounts', 'MapSettings')
    MapSettings.objects.filter(default_map_type__in=['', 'roadmap', 'satellite']).update(default_map_type='hybrid')


def restore_existing_map_settings_to_roadmap(apps, schema_editor):
    MapSettings = apps.get_model('accounts', 'MapSettings')
    MapSettings.objects.filter(default_map_type='hybrid').update(default_map_type='roadmap')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_mapsettings_default_map_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='default_map_type',
            field=models.CharField(
                choices=[
                    ('roadmap', 'Roadmap (Default)'),
                    ('hybrid', 'Satellite (with roads & labels)'),
                ],
                default='hybrid',
                max_length=20,
            ),
        ),
        migrations.RunPython(set_existing_map_settings_to_hybrid, restore_existing_map_settings_to_roadmap),
    ]
