export const COLORS = {
  surfaceContainerLow: "#f3f3f3",
  onTertiary: "#ffffff",
  onPrimaryFixedVariant: "#005227",
  onPrimary: "#ffffff",
  secondaryFixed: "#ffd6f9",
  primaryFixed: "#79fca0",
  primaryContainer: "#0fa958",
  inversePrimary: "#5bdf87",
  onSurface: "#1a1c1c",
  inverseSurface: "#2f3131",
  outlineVariant: "#bccabb",
  onSecondary: "#ffffff",
  onErrorContainer: "#93000a",
  outline: "#6d7b6d",
  surfaceVariant: "#e2e2e2",
  inverseOnSurface: "#f1f1f1",
  primary: "#006d36",
  onTertiaryFixedVariant: "#474747",
  onSecondaryFixedVariant: "#79197e",
  surface: "#f9f9f9",
  tertiaryContainer: "#939393",
  background: "#f9f9f9",
  error: "#ba1a1a",
  surfaceContainerLowest: "#ffffff",
  secondaryContainer: "#fc92fb",
  onPrimaryContainer: "#003416",
  surfaceDim: "#dadada",
  surfaceContainer: "#eeeeee",
  surfaceTint: "#006d36",
  tertiaryFixedDim: "#c6c6c6",
  errorContainer: "#ffdad6",
  onSecondaryFixed: "#37003b",
  primaryFixedDim: "#5bdf87",
  onError: "#ffffff",
  secondaryFixedDim: "#ffa9fb",
  onSurfaceVariant: "#3d4a3e",
  tertiaryFixed: "#e2e2e2",
  surfaceBright: "#f9f9f9",
  secondary: "#953699",
  surfaceContainerHighest: "#e2e2e2",
  onTertiaryFixed: "#1b1b1b",
  onSecondaryContainer: "#7c1c81",
  onBackground: "#1a1c1c",
  surfaceContainerHigh: "#e8e8e8",
  onTertiaryContainer: "#2c2c2c",
  onPrimaryFixed: "#00210c",
  tertiary: "#5e5e5e"
};

export const FONTS = {
  bodyLg: { fontSize: 18, lineHeight: 28, fontWeight: '400' as const },
  labelLg: { fontSize: 14, lineHeight: 16, letterSpacing: 0.14, fontWeight: '600' as const },
  headlineMd: { fontSize: 20, lineHeight: 28, fontWeight: '700' as const },
  bodyMd: { fontSize: 16, lineHeight: 24, fontWeight: '400' as const },
  bodySm: { fontSize: 14, lineHeight: 20, fontWeight: '400' as const },
  headlineXl: { fontSize: 32, lineHeight: 40, letterSpacing: -0.64, fontWeight: '800' as const },
  headlineLg: { fontSize: 24, lineHeight: 32, letterSpacing: -0.24, fontWeight: '700' as const },
  labelMd: { fontSize: 12, lineHeight: 14, letterSpacing: 0.24, fontWeight: '600' as const },
};

export const AMBIENT_SHADOW = {
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 8 },
  shadowOpacity: 0.05,
  shadowRadius: 24,
  elevation: 4,
};
