"""Enterprise report catalog — 55+ definitions + 5 packages."""

REPORT_CATEGORIES = [
    {'key': 'treasury', 'label': 'Platform Treasury', 'icon': 'account_balance'},
    {'key': 'rides', 'label': 'Ride Economics', 'icon': 'local_taxi'},
    {'key': 'gateway', 'label': 'Gateway & Payments', 'icon': 'account_balance_wallet'},
    {'key': 'payouts', 'label': 'Driver Payouts', 'icon': 'send'},
    {'key': 'disputes', 'label': 'Refunds & Disputes', 'icon': 'gavel'},
    {'key': 'risk', 'label': 'Risk & Exceptions', 'icon': 'warning'},
    {'key': 'compliance', 'label': 'Compliance & Audit', 'icon': 'policy'},
    {'key': 'students', 'label': 'Student Wallet (Aggregate)', 'icon': 'school'},
    {'key': 'operations', 'label': 'Operations & Fleet', 'icon': 'route'},
    {'key': 'packages', 'label': 'Report Packages', 'icon': 'folder_zip'},
    {'key': 'consent', 'label': 'Consent Statements', 'icon': 'verified_user'},
]


def _r(key, title, category, desc, formats=None, consent=False):
    return {
        'key': key,
        'title': title,
        'category': category,
        'description': desc,
        'formats': formats or ['csv', 'pdf', 'xlsx'],
        'consent_required': consent,
    }


REPORT_CATALOG = [
    _r('platform_ledger', 'Platform Ledger', 'treasury', 'Anonymized platform event log.'),
    _r('commission_summary', 'Commission Summary', 'treasury', 'Platform commission totals and trends.'),
    _r('gross_ride_volume', 'Gross Ride Volume', 'treasury', 'Total fares processed (aggregate).'),
    _r('net_settlement', 'Net Settlement Position', 'treasury', 'Commission minus refunds and chargebacks.'),
    _r('daily_cash_position', 'Daily Cash Position', 'treasury', 'End-of-day money flow snapshot.'),
    _r('monthly_revenue', 'Monthly Revenue Statement', 'treasury', 'Formal monthly treasury statement.'),
    _r('quarterly_executive', 'Quarterly Executive Summary', 'treasury', 'Board-ready executive summary.'),
    _r('ytd_revenue', 'Year-to-Date Revenue', 'treasury', 'Fiscal YTD commission roll-up.'),
    _r('campus_comparison', 'Campus Comparison', 'treasury', 'Cross-campus revenue comparison.'),
    _r('revenue_by_vehicle', 'Revenue by Vehicle Type', 'treasury', 'Commission split by vehicle type.'),
    _r('completed_rides_register', 'Completed Rides Register', 'rides', 'Completed rides with fares and routes.'),
    _r('cancelled_rides_analysis', 'Cancelled Rides Analysis', 'rides', 'Cancellations and lost revenue.'),
    _r('avg_fare_trend', 'Average Fare Trend', 'rides', 'Average fare over time.'),
    _r('surge_impact', 'Surge Impact Report', 'rides', 'Revenue when surge multiplier > 1.'),
    _r('distance_duration_stats', 'Distance & Duration Stats', 'rides', 'Trip distance and duration aggregates.'),
    _r('peak_hours', 'Peak Hours Export', 'rides', 'Hourly ride volume data.'),
    _r('route_performance', 'Route Performance', 'rides', 'Top corridors by rides and commission.'),
    _r('no_show_summary', 'No-Show & Penalty Summary', 'rides', 'No-show fees collected.'),
    _r('completion_rate', 'Ride Completion Rate', 'rides', 'Completed vs total requested.'),
    _r('payment_method_mix', 'Payment Method Mix', 'rides', 'Wallet vs card vs cash breakdown.'),
    _r('gateway_reconciliation', 'Gateway Reconciliation', 'gateway', 'Paystack vs Flutterwave vs wallet credits.'),
    _r('topup_success_rate', 'Top-Up Success Rate', 'gateway', 'Gateway success/failure rates.'),
    _r('failed_topups', 'Failed Top-Ups Register', 'gateway', 'Failed and abandoned top-ups.'),
    _r('topup_by_channel', 'Top-Up by Channel', 'gateway', 'Volume by payment channel.'),
    _r('webhook_log', 'Webhook Processing Log', 'gateway', 'Webhook events received.'),
    _r('gateway_settlement_lag', 'Gateway Settlement Lag', 'gateway', 'Time from initiation to credit.'),
    _r('duplicate_idempotency', 'Duplicate Idempotency Audit', 'gateway', 'Duplicate reference detection.'),
    _r('chargeback_register', 'Chargeback & Reversal Register', 'gateway', 'Reversed gateway transactions.'),
    _r('driver_withdrawal_summary', 'Driver Withdrawal Summary', 'payouts', 'Aggregate driver payout totals.'),
    _r('pending_payouts', 'Pending Payouts Queue', 'payouts', 'Pending and processing withdrawals.'),
    _r('failed_payouts', 'Failed Payouts Register', 'payouts', 'Failed bank transfers.'),
    _r('payout_fees', 'Payout Fees & Costs', 'payouts', 'Transfer fees summary.'),
    _r('driver_earnings_pool', 'Driver Earnings Pool', 'payouts', 'Total driver earnings (aggregate).'),
    _r('commission_driver_share', 'Commission vs Driver Share', 'payouts', 'Platform vs driver split verification.'),
    _r('payout_sla', 'Payout SLA Report', 'payouts', 'Withdrawal processing times.'),
    _r('bank_distribution', 'Bank Distribution', 'payouts', 'Payouts by bank (masked).'),
    _r('dispute_register', 'Dispute Register', 'disputes', 'All disputed rides.'),
    _r('open_disputes_aging', 'Open Disputes Aging', 'disputes', 'Days open for unresolved disputes.'),
    _r('refunds_issued', 'Refunds Issued', 'disputes', 'Ride refunds credited to wallets.'),
    _r('refund_reason_analysis', 'Refund Reason Analysis', 'disputes', 'Refunds by cancellation type.'),
    _r('admin_refund_actions', 'Admin Refund Actions', 'disputes', 'Admin-initiated refunds audit.'),
    _r('dispute_resolution_sla', 'Dispute Resolution SLA', 'disputes', 'Time to resolve disputes.'),
    _r('failed_transactions_master', 'Failed Transactions Master', 'risk', 'All failed platform events.'),
    _r('needs_action_queue', 'Needs Action Queue', 'risk', 'Items requiring admin attention.'),
    _r('anomaly_detection', 'Anomaly Detection Export', 'risk', 'Unusual volume spikes.'),
    _r('wallet_integrity', 'Wallet Integrity Check', 'risk', 'Ledger consistency summary.'),
    _r('orphan_transactions', 'Orphan Transaction Scan', 'risk', 'Transactions without ride links.'),
    _r('stale_pending', 'Stale Pending Report', 'risk', 'Pending items older than threshold.'),
    _r('admin_audit_trail', 'Admin Audit Trail', 'compliance', 'Admin financial and security actions.'),
    _r('statement_access_log', 'Statement Access Log', 'compliance', 'Consented statement downloads.'),
    _r('report_generation_log', 'Report Generation Log', 'compliance', 'All report runs meta-audit.'),
    _r('ndpr_consent_register', 'NDPR Consent Register', 'compliance', 'Users with data consent flags.'),
    _r('role_access_changes', 'Role & Access Changes', 'compliance', 'Role change audit entries.'),
    _r('ip_session_audit', 'IP & Session Audit', 'compliance', 'Sensitive actions by IP.'),
    _r('student_topup_volume', 'Top-Up Volume (Students)', 'students', 'Aggregate student wallet top-ups.'),
    _r('student_ride_payment_volume', 'Ride Payment Volume', 'students', 'Aggregate wallet ride payments.'),
    _r('student_refund_volume', 'Refund Volume to Students', 'students', 'Aggregate student refunds.'),
    _r('promotional_credits', 'Promotional Credits Issued', 'students', 'Promotion credits summary.'),
    _r('rides_by_zone', 'Rides by Campus Zone', 'operations', 'Rides grouped by pickup area.'),
    _r('garage_scan_summary', 'Garage Scan-to-Pay Summary', 'operations', 'Garage ride payment summary.'),
    _r('drivers_vs_volume', 'Drivers vs Ride Volume', 'operations', 'Supply vs demand ratio.'),
    _r('vehicle_utilization', 'Vehicle Type Utilization', 'operations', 'Utilization by vehicle type.'),
    _r('daily_ops_pack', 'Daily Ops Pack', 'packages', 'Ledger + failed tx + open disputes.', ['zip']),
    _r('weekly_finance_pack', 'Weekly Finance Pack', 'packages', 'Commission + gateway recon + payouts.', ['zip']),
    _r('monthly_board_pack', 'Monthly Board Pack', 'packages', 'Executive summary + monthly revenue + audit.', ['zip']),
    _r('quarterly_compliance_pack', 'Quarterly Compliance Pack', 'packages', 'Audit + consent + reconciliation.', ['zip']),
    _r('incident_pack', 'Incident Pack', 'packages', 'Disputes + refunds + admin actions.', ['zip']),
    _r('driver_earnings_statement', 'Driver Earnings Statement', 'consent', 'Personal driver wallet statement.', consent=True),
    _r('driver_tax_summary', 'Driver Tax / Earnings Summary', 'consent', 'Annual-style earnings summary.', consent=True),
    _r('student_wallet_statement', 'Student Wallet Statement', 'consent', 'Personal student wallet statement.', consent=True),
    _r('single_ride_receipt', 'Single Ride Receipt', 'consent', 'Receipt for one ride.', consent=True),
]

PACKAGE_CONTENTS = {
    'daily_ops_pack': ['platform_ledger', 'failed_transactions_master', 'open_disputes_aging'],
    'weekly_finance_pack': ['commission_summary', 'gateway_reconciliation', 'driver_withdrawal_summary'],
    'monthly_board_pack': ['monthly_revenue', 'quarterly_executive', 'admin_audit_trail'],
    'quarterly_compliance_pack': ['admin_audit_trail', 'statement_access_log', 'gateway_reconciliation'],
    'incident_pack': ['dispute_register', 'refunds_issued', 'admin_refund_actions'],
}

CATALOG_BY_KEY = {item['key']: item for item in REPORT_CATALOG}
