# Generated by Django 5.1.4 on 2026-06-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsnapshot',
            name='location_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
