# Generated by Django 5.1.4 on 2026-08-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_add_location_count_to_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('lecture', 'Lecture Theatre'), ('hostel', 'Hostel'), ('gate', 'Gate'), ('library', 'Library'), ('blocks', 'Admin / General Block'), ('medical', 'Medical Centre'), ('sports', 'Sports Facility'), ('ict', 'ICT Centre'), ('canteen', 'Canteen / Cafeteria'), ('mosque', 'Mosque'), ('laboratory', 'Laboratory'), ('bosso', 'Bosso'), ('talba', 'Talba'), ('kpakungu', 'Kpakungu'), ('maitumbi', 'Maitumbi'), ('tunga', 'Tunga'), ('chanchaga', 'Chanchaga'), ('minna_central', 'Minna Central'), ('kwamba', 'Kwamba'), ('sango', 'Sango'), ('dutsen_kura', 'Dutsen Kura'), ('barkin_sale', 'Barkin Sale'), ('mobile', 'Mobile Layout'), ('gbangban', 'Gbangban'), ('sauka_kahuta', 'Sauka Kahuta'), ('shango', 'Shango'), ('aliyu_makama', 'Aliyu Makama Road'), ('paikon_kore', 'Paikon Kore'), ('maikunkele', 'Maikunkele'), ('ibb_way', 'IBB Way'), ('airport_road', 'Airport Road'), ('wushishi', 'Wushishi'), ('faith_gate', 'Faith Gate Area'), ('others', 'Others')], db_index=True, max_length=30),
        ),
    ]
