# Generated by Django 5.1.4 on 2026-08-04
# Data migration: rename 'mosque' category to 'worship' (Place of Worship) for
# religious neutrality, and alter field choices to include new institutional categories.

from django.db import migrations, models


def rename_mosque_to_worship(apps, schema_editor):
    Location = apps.get_model('locations', 'Location')
    Location.objects.filter(category='mosque').update(category='worship')


def reverse_worship_to_mosque(apps, schema_editor):
    Location = apps.get_model('locations', 'Location')
    Location.objects.filter(category='worship').update(category='mosque')


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_add_minna_region_categories'),
    ]

    operations = [
        migrations.RunPython(rename_mosque_to_worship, reverse_worship_to_mosque),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(
                choices=[
                    ('lecture', 'Lecture Theatre'),
                    ('hostel', 'Hostel'),
                    ('gate', 'Gate'),
                    ('library', 'Library'),
                    ('blocks', 'Admin / General Block'),
                    ('medical', 'Medical Centre'),
                    ('sports', 'Sports Facility'),
                    ('ict', 'ICT Centre'),
                    ('canteen', 'Canteen / Cafeteria'),
                    ('worship', 'Place of Worship'),
                    ('laboratory', 'Laboratory'),
                    ('workshop', 'Workshop / Tech Lab'),
                    ('auditorium', 'Auditorium / Hall'),
                    ('parking', 'Parking Area'),
                    ('faculty', 'Faculty / Department Office'),
                    ('senate', 'Senate / Admin Directorate'),
                    ('bosso', 'Bosso'),
                    ('talba', 'Talba'),
                    ('kpakungu', 'Kpakungu'),
                    ('maitumbi', 'Maitumbi'),
                    ('tunga', 'Tunga'),
                    ('chanchaga', 'Chanchaga'),
                    ('minna_central', 'Minna Central'),
                    ('kwamba', 'Kwamba'),
                    ('sango', 'Sango'),
                    ('dutsen_kura', 'Dutsen Kura'),
                    ('barkin_sale', 'Barkin Sale'),
                    ('mobile', 'Mobile Layout'),
                    ('gbangban', 'Gbangban'),
                    ('sauka_kahuta', 'Sauka Kahuta'),
                    ('shango', 'Shango'),
                    ('aliyu_makama', 'Aliyu Makama Road'),
                    ('paikon_kore', 'Paikon Kore'),
                    ('maikunkele', 'Maikunkele'),
                    ('ibb_way', 'IBB Way'),
                    ('airport_road', 'Airport Road'),
                    ('wushishi', 'Wushishi'),
                    ('faith_gate', 'Faith Gate Area'),
                    ('others', 'Others'),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
