# Generated by Django 5.1.4 on 2026-04-30 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_reference', models.CharField(max_length=40, unique=True)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=20)),
                ('gateway_status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('reversed', 'Reversed')], db_index=True, default='initiated', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('channel', models.CharField(blank=True, max_length=40)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gateway_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gateway_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'gateway_status'], name='gateway_tra_user_id_915ad7_idx'), models.Index(fields=['gateway', 'gateway_status'], name='gateway_tra_gateway_c772c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], db_index=True, max_length=10)),
                ('source', models.CharField(choices=[('ride_payment', 'Ride Payment'), ('ride_refund', 'Ride Refund'), ('topup_paystack', 'Top-Up via Paystack'), ('topup_flutterwave', 'Top-Up via Flutterwave'), ('driver_earning', 'Driver Earning'), ('driver_withdrawal', 'Driver Withdrawal'), ('platform_commission', 'Platform Commission'), ('promotion', 'Promotional Credit'), ('admin_adjustment', 'Admin Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('narration', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='wallet_tran_user_id_5cf180_idx'), models.Index(fields=['ride'], name='wallet_tran_ride_id_449614_idx')],
            },
        ),
    ]
