# Generated by Django 5.1.4 on 2026-05-04 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaytransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=20)),
                ('event_id', models.CharField(db_index=True, max_length=120)),
                ('reference', models.CharField(blank=True, max_length=40, null=True)),
                ('signature_hash', models.CharField(db_index=True, max_length=128)),
                ('payload_hash', models.CharField(max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-received_at'],
                'indexes': [
                    models.Index(fields=['gateway', 'event_id'], name='webhook_eve_gateway_1c2756_idx'),
                    models.Index(fields=['gateway', 'signature_hash'], name='webhook_eve_gateway_74a56e_idx'),
                    models.Index(fields=['gateway', 'reference'], name='webhook_eve_gateway_fdf78e_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('gateway', 'event_id'), name='webhook_event_gateway_event_id_uniq'),
                    models.UniqueConstraint(fields=('gateway', 'signature_hash'), name='webhook_event_gateway_sig_uniq'),
                ],
            },
        ),
    ]
