# Generated by Django 5.1.4 on 2026-05-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_add_webhook_event_and_idempotency"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="webhook_eve_gateway_bf0918_idx",
            old_name="webhook_eve_gateway_1c2756_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="webhook_eve_gateway_5cf5c6_idx",
            old_name="webhook_eve_gateway_74a56e_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="webhook_eve_gateway_607e7f_idx",
            old_name="webhook_eve_gateway_fdf78e_idx",
        ),
    ]
