# Generated by Django 5.1.4 on 2026-08-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_gatewaytransaction_wallet_credited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('ride_payment', 'Ride Payment'), ('ride_refund', 'Ride Refund'), ('topup_paystack', 'Top-Up via Paystack'), ('topup_flutterwave', 'Top-Up via Flutterwave'), ('student_transfer_sent', 'Student Transfer Sent'), ('student_transfer_received', 'Student Transfer Received'), ('driver_earning', 'Driver Earning'), ('driver_withdrawal', 'Driver Withdrawal'), ('platform_commission', 'Platform Commission'), ('promotion', 'Promotional Credit'), ('driver_penalty', 'Driver Penalty'), ('admin_adjustment', 'Admin Adjustment')], max_length=30),
        ),
    ]
